edition = "2024"
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
normalize_comments = true
wrap_comments = false
format_code_in_doc_comments = true
chain_width = 60
max_width = 100
match_arm_leading_pipes = "Never"
use_field_init_shorthand = true
remove_nested_parens = true
