[package]
name = "gallry-puzzle-soulver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "word_generator_benchmark"
harness = false
